### ISSUE TITLE
Does yunikorn support Hadoop-mapreduce workload on k8s?

### ISSUE THREAD

**Issue by wongxingjun** [cloudera/yunikorn-core#16]
Does yunikorn support Hadoop-mapreduce workload on k8s?

**Comment by yangwwei** [comment]
Hi @wongxingjun 

YuniKorn is a scheduler, it should be general enough to support MR workloads, which spawns a large number of small-batch tasks. However, to run MR on K8s, there is some more work to be done at 2nd level scheduling, like the MR-app-master in YARN. In K8s world, it can be a controller. This is out of the scope of YuniKorn.

**Comment by wongxingjun** [comment]
Thanks for your reply.  Acctually, a complex k8s controller or a customized operator is needed to figure out this problem.
