### ISSUE TITLE
UT failure acl_test#TestACLSpecialCase

### ISSUE THREAD

**Issue by yangwwei** [cloudera/yunikorn-core#49]

**Comment by yangwwei** [comment]
Hi @wilfred-s 
I temporarily commented out the failed test in commit: https://github.com/cloudera/yunikorn-core/commit/68f42a51d4f0f2b9ea313008d16e6ed05e2068d5
When you get back, pls take a look and fix this instead.
Thanks

**Comment by wilfred-s** [comment]
In pr #40 I fixed up the regexp for the group and made sure that the config and ACL now use the same version. The regexp that was used in the ACL was more restrictive than the config which was incorrect.
The specified user is valid in the ACL.

I'll create a fix for this.

**Comment by yangwwei** [comment]
Thanks @wilfred-s

**Comment by yangwwei** [comment]
this is fixed by #58
