### ISSUE TITLE
TestConfigWatcherExpiration UT fails intermittently

### ISSUE THREAD

**Issue by TaoYang526** [cloudera/yunikorn-core#62]
=== RUN   TestConfigWatcherExpiration
2019-11-05T18:20:48.643+0800       DEBUG  configs/configwatcher.go:92 configuration file unchanged
2019-11-05T18:20:49.646+0800       DEBUG  configs/configwatcher.go:92 configuration file unchanged
2019-11-05T18:20:50.647+0800       DEBUG  configs/configwatcher.go:92 configuration file unchanged
2019-11-05T18:20:51.651+0800       DEBUG  configs/configwatcher.go:92 configuration file unchanged
--- FAIL: TestConfigWatcherExpiration (5.01s)
    configwatcher_test.go:133: assertion failed: expression is false: waitForStopped(cw) == nil
FAIL

Referenced code:
```
// if configWatcher is not running, kick-off running it
// if configWatcher is already running, this is a noop
func (cw *ConfigWatcher) Run() {
	select {
	case cw.soloChan <- 0:
		ticker := time.NewTicker(1 * time.Second)
		quit := make(chan bool)
		go func() {
			for {
				select {
				case <-ticker.C:
					if !cw.runOnce() {
						<-cw.soloChan
						return
					}
				case <-quit:
					<-cw.soloChan
					ticker.Stop()
					return
				}
			}
		}()

		time.AfterFunc(cw.expireTime, func() {
			quit <- true
		})
	default:
		log.Logger().Info("config watcher is already running")
	}
}
```

The cause of this failure is that golang select statement will randomly choose a case when multiple cases can run, we can't guarantee that it can quit in 5 seconds which is the stop timeout defined in TestConfigWatcherExpiration.
I think perhaps we can add a new select statement with default case ahead of this select statement then move the quit case inside, so that it always check quit case first and will go forward to tick if not satisfied, in this way, it can quit after one tick interval at most after expired.
New code like this:
```
		go func() {
			for {
				select {
				case <-quit:
					<-cw.soloChan
					ticker.Stop()
					return
				default:
				}
				select {
				case <-ticker.C:
					if !cw.runOnce() {
						<-cw.soloChan
						return
					}
				}
			}
		}()
```
Looking forward to your feedbacks, thanks!

**Comment by yangwwei** [comment]
Hi @TaoYang526 

It makes sense, can you submit a patch for this? Thanks a lot!
